// Globe.jsx
// Rotating dotted-Earth globe, ported from the standalone "Travel Dream Card"
// artifact into a React component. Renders a <canvas> driven by requestAnimationFrame.
//
// Land cells come from a packed 360x180 (1°) bitmap, base64-encoded. Points are
// distributed over the sphere with a Fibonacci lattice; only front-hemisphere
// land points are drawn each frame.
//
// Usage: <Globe className="hobby-globe" size={1440} />

import { useRef, useEffect } from "react";

export function Globe({ className = "", size = 640 }) {
  const ref = useRef(null);

  useEffect(() => {
    const cvs = ref.current;
    if (!cvs) return;
    const ctx = cvs.getContext("2d");
    const W = cvs.width, H = cvs.height;
    const CX = W / 2, CY = H / 2;
    const R = Math.min(W, H) * 0.44;

    // Land mask: 360x180 bitmap (1° cells), 1 bit per cell, LSB-first, base64.
    const LAND_B64 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPD//w8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P////8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P////8DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P////8DAAAAAAAAAAAAAAAAwP9/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P////8BAAAAAAAAAAAAAID//////z8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P////8AAAAAAAAAAAAA4P//////////AAAAAAAAAAAAAAAAAAAAAAAAAAAA4P///38AAAAAAAAAAAAA////////////BwAAAAAAAAAAgP//fwAAAAAAAAAAwP///z8AAAAAAHwAAACA////////////PwAAAAAAAAAAAADw//8/AAAAAAAAwP///x8AAAAAgP8HAACA/////////////w8AAAAAAAAAAAAA/v///wMAAAAAwP///wMAAAAA4P//AADA//////////////8HAAAAAAAAAAAA/////x8AAAAAgP//fwAAAAAA/P//DwDg////////////////BwAAAAAAAACA/////z8AAAAAgP//HwAAAAAA////HwDw/////////////////wcAAAAAAADA/////38AAAAAgP//AwAcAACA////HwD4//////////////////8DAPz///////////////////////////////////8HAAAAAAAAAAAAAAAAAAAAAPj///////////////////////////////////8HAAAAAAAAAAAAAAAAAAAAAPD///////////////////////////////////8HAAAAAADA////////DwAAAOD//////////////////////////wH+////DwD4////////////////BwAAAMD///////////////8AAMAAAAAAAAD+////DwD4////////////////AwAAAAAAAAD8//////////8PAAAAAAAAAID/////DwD8////////////////AwAAAAAAAADA//////////8fAAAAAAAAAPz/////BwD+////////////////AQAAAAAAAACA//////////9/AAAAAAAAwP//////AwD/////////////////AQAAAAAAAAAA////////////AAAAAAAA4P//////A4D/////////////////AAAAAAAAAAAA/v//////////AQAAAAAAwP//////AcD///////////////9/AAAAAAAAAAAA/P//////////BwAAAAAA2P//////AcD/////////////////AAAAAAAAAAAA+P//////////DwAAAAAA/P//////AYD/////////////////BwAAAAAAAAAA8P//////////DwAAAAAAvP//////AYD/////////////////BwAAAAAAAAAA4P//////////DwAAAAAAjP//////AYD/////////////////AwAAAAAAAAAAwP//////////BwAAAAAAgP//////AQD/////////////////AQAAAAAAAAAAgP//////////AwAAAAAAgP//////AQD/////////////////AAAAAAAAAAAAgP//////////AQAAAAAAgP//////AYD///////////////9/AAAAAAAAAAAAgP//////////AQAAAAAAgP//////AYD///////////////8PAAAAAAAAAAAAgP//////////AAAAAAAAAP////9/AID//////////////38AAAAAAAAAAAAAgP////////9/AAAAAAAAAP////8PAMD//////////////wMAAAAAAAAAAAAAgP////////8PAAAAAAAAAP7/8/8BAMD/////////////fwQAAAAAAAAAAAAAAP////////8AAAAAAAAAAPz/4f8AAOD/////////////Hw4AAAAAAAAAAAAAAP///////38AAAAAAAAAAAD+wP8AAOD/////////////Bw8AAAAAAAAAAAAAAP///////z8AAAAAAAAAAAD8gP8AAOD/////////////AQMAAAAAAAAAAAAAAP///////wcAAAAAAAAAAAD4B38AAPD/////////////AAEAAAAAAAAAAAAAAP///////wMAAAAAAAAAAADwHwAAAPD///////////8/AAEAAAAAAAAAAAAAAP7//////wEAAAAAAAAAAAAADxwAAOD///////////8fAAEAAAAAAAAAAAAAAPz//////wAAAAAAAAAAAAAAAPgAAOD///////////8PgAEAAAAAAAAAAAAAAPz//////wAAAAAAAAAAAAAAAOCBAcD///////////8HwAAAAAAAAAAAAAAAAPj//////wAAAAAAAAAAAAAAAACGH8D///////////8D8AAAAAAAAAAAAAAAAPD/////fwAAAAAAAAAA4D8AAACAf8D///////////8DfgAAAAAAAAAAAAAAAOD/////PwAAAAAAAAAA8P8HAACA/8D///////////8DDgAAAAAAAAAAAAAAAMD/////HwAAAAAAAAAA+P//DwCA/8H///////////8BAAAAAAAAAAAAAAAAAID/////DwAAAAAAAAAA/P///3/A/8P///////////8AAAAAAAAAAAAAAAAAAAD/////BwAAAAAAAAAA/v/////P/8f//////////38AAAAAAAAAAAAAAAAAAAD+////BwAAAAAAAAAA///////f/4///////////z8AAAAAAAAAAAAAAAAAAAD4////AwAAAAAAAACA///////f/x///////////x8AAAAAAAAAAAAAAAAAAADw////CwAAAAAAAACA//////+//x/8/////////w8AAAAAAAAAAAAAAAAAAADg////AwAAAAAAAADA//////+//z/g/////////w8AAAAAAAAAAAAAAAAAAACA////AQAAAAAAAADg//////9//38A/////////wcAAAAAAAAAAAAAAAAAAAAA////AQAAAAAAAADw//////9//v8A+P///////wMAAAAAAAAAAAAAAAAAAAAA/v//AQAAAAAAAAD4//////9//P8BwP///////wAAAAAAAAAAAAAAAAAAAAAA+P//AAAAAAAAAAD4////////+P8DAP//////DwAAAAAAAAAAAAAAAAAAAAAA4P9/AAAAAAAAAAD4////////+P8HAP7/h///AQAAAAAAAAAAAAAAAAAAAAAAgP8/AAAAAAAAAADw////////8f8HAPz/A/7/AAAAAAAAAAAAAAAAAAAAAAAAAPwHAAAAAAAAAADw////////4f8DAPj/APz/AAAAAAAAAAAAAAAAAAAAAAAAAPAHAAAAAAAAAADw////////w/8DAPB/APz/AAAAAAAAAAAAAAAAAAAAAAAAAKADAAAAAAAAAADw////////x/8DAPA/APz/AAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAD4////////x/8BAPAfAPj/ADAAAAAAAAAAAAAAAAAAAAAAAIADAAAAAAAAAAD4////////z/8AAPAPAPj/ADAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAD4////////jz8AAOAPAPD/AHAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAD4////////nx8AAOAHAOD/AOAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAADw////////PwAAAOAHAMD/AMAAAAAAAAAAAAAAAAAAAAAAAADAAAwAAAAAAADw////////fwAAAOADAID/AMABAAAAAAAAAAAAAAAAAAAAAACAA/8AAAAAAADg/////////wAAAOADAID/AMADAAAAAAAAAAAAAAAAAAAAAAAAR/8PAAAAAADg/////////wcAAMADAIAHAIADAAAAAAAAAAAAAAAAAAAAAAAAvv9/AAAAAADA/////////wcAAMABAAABAIABAAAAAAAAAAAAAAAAAAAAAAAAgP//AQAAAACA/////////wMAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAgP//DwAAAAAA/////////wEAAAAAAAAAgAEAAAAAAAAAAAAAAAAAAAAAAAAAgP//fwAAAAAA+PH//////wAAAAAAAAAA8AEAAAAAAAAAAAAAAAAAAAAAAAAAgP///wAAAAAAMAD/////fwAAAAAAABgA/gEAAAAAAAAAAAAAAAAAAAAAAAAAwP///wEAAAAAAAD+////PwAAAAAAAPDD/wEAAAAAAAAAAAAAAAAAAAAAAAAA4P///wEAAAAAAAD8////PwAAAAAAAOD//wEAAAAAAAAAAAAAAAAAAAAAAAAA4P///wMAAAAAAAD4////HwAAAAAAAMD//wEAAAAAAAAAAAAAAAAAAAAAAAAA8P///wcAAAAAAADw////HwAAAAAAAID//wEAAAAAAAAAAAAAAAAAAAAAAAAA8P///z8AAAAAAADg////HwAAAAAAAAD//wEAAAAAAAAAAAAAAAAAAAAAAAAA8P////8AAAAAAADA////DwAAAAAAAAD+/wEAHwAAAAAAAAAAAAAAAAAAAAAA+P////8HAAAAAADA////DwAAAAAAAAD8/wEA/gEAAAAAAAAAAAAAAAAAAAAA+P////8fAAAAAACA////DwAAAAAAAAD4/wMA+AMAAAAAAAAAAAAAAAAAAAAA+P//////AAAAAACA////DwAAAAAAAADw/wcAwA8AAAAAAAAAAAAAAAAAAAAA+P//////AQAAAAAA////DwAAAAAAAADg/w8AAB8AAAAAAAAAAAAAAAAAAAAA8P//////AQAAAAAA////DwAAAAAAAAAA/wcAAD4AAAAAAAAAAAAAAAAAAAAA8P//////AQAAAAAA////DwAAAAAAAAAA8AMAAHwAAAAAAAAAAAAAAAAAAAAA4P//////AQAAAAAA////DwAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAwP//////AAAAAAAA/v//DwAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAwP////9/AAAAAAAA/v//DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP////8/AAAAAAAA/v//DwAAAAAAAAAAAACA/wMAAAAAAAAAAAAAAAAAAAAAAP////8/AAAAAAAA/v//DwAAAAAAAAAAAADA/wcAAAAAAAAAAAAAAAAAAAAAAP7///8/AAAAAAAA/v//DxAAAAAAAAAAAADw/w8AAAAAAAAAAAAAAAAAAAAAAPz///8/AAAAAAAA/v//DzgAAAAAAAAAAAD+/x8AAAAAAAAAAAAAAAAAAAAAAPj///8fAAAAAAAA////DzwAAAAAAAAAAAD//z8AAAAAAAAAAAAAAAAAAAAAAPD///8fAAAAAAAA////Bx4AAAAAAAAAAID//z8AAAAAAAAAAAAAAAAAAAAAAOD///8fAAAAAAAA////Ax8AAAAAAAAAAMD//38AAAAAAAAAAAAAAAAAAAAAAMD///8fAAAAAAAA////AR8AAAAAAAAAAOD///8AAAAAAAAAAAAAAAAAAAAAAMD///8PAAAAAAAA////AQ8AAAAAAAAAAPD///8BAAAAAAAAAAAAAAAAAAAAAMD///8PAAAAAAAA/v//AA8AAAAAAAAAAPz///8BAAAAAAAAAAAAAAAAAAAAAMD///8PAAAAAAAA/v9/AA8AAAAAAAAAAP////8DAAAAAAAAAAAAAAAAAAAAAMD///8HAAAAAAAA/v9/AAcAAAAAAAAAgP////8HAAAAAAAAAAAAAAAAAAAAAMD///8DAAAAAAAA/P8/AAcAAAAAAAAAwP////8PAAAAAAAAAAAAAAAAAAAAAMD///8BAAAAAAAA/P8fAAIAAAAAAAAAwP////8fAAAAAAAAAAAAAAAAAAAAAMD//38AAAAAAAAA/P8fAAAAAAAAAAAAwP////8fAAAAAAAAAAAAAAAAAAAAAMD//z8AAAAAAAAA+P8PAAAAAAAAAAAAwP////8fAAAAAAAAAAAAAAAAAAAAAOD//x8AAAAAAAAA+P8PAAAAAAAAAAAAwP////8fAAAAAAAAAAAAAAAAAAAAAOD//wcAAAAAAAAA+P8HAAAAAAAAAAAAwP////8fAAAAAAAAAAAAAAAAAAAAAOD//wMAAAAAAAAA8P8DAAAAAAAAAAAAwP////8PAAAAAAAAAAAAAAAAAAAAAPD//wEAAAAAAAAA8P8BAAAAAAAAAAAAwP////8PAAAAAAAAAAAAAAAAAAAAAPD//wAAAAAAAAAA4P8AAAAAAAAAAAAAgP////8PAAAAAAAAAAAAAAAAAAAAAPD/fwAAAAAAAAAA4H8AAAAAAAAAAAAAgP8B//8PAAAAAAAAAAAAAAAAAAAAAPj/PwAAAAAAAAAAwD8AAAAAAAAAAAAAAD8A+P8HAAAAAAAAAAAAAAAAAAAAAPj/HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAYA4P8DAAAAAAAAAAAAAAAAAAAAAPj/DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP8BAAAEAAAAAAAAAAAAAAAAAPj/BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAIAAAAAAAAAAAAAAAAAPj/AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4AAAAQAAAAAAAAAAAAAAAAAPj/AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAYAAAAAAAAAAAAAAAAAPh/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAPw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAPwPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAPwHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAPwDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAPwDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAPwBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAPwBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    const MW = 360, MH = 180;
    const landBits = (() => {
      const bin = atob(LAND_B64);
      const u = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) u[i] = bin.charCodeAt(i);
      return u;
    })();
    function isLand(lat, lng) {
      let x = Math.floor(lng + 180);
      let y = Math.floor(90 - lat);
      if (x < 0) x = 0; if (x >= MW) x = MW - 1;
      if (y < 0) y = 0; if (y >= MH) y = MH - 1;
      const idx = y * MW + x;
      return (landBits[idx >> 3] >> (idx & 7)) & 1;
    }

    // Distribute points over the sphere with a Fibonacci lattice.
    const N = 5000;
    const pts = [];
    const golden = Math.PI * (3 - Math.sqrt(5));
    for (let i = 0; i < N; i++) {
      const y = 1 - (i / (N - 1)) * 2;
      const r = Math.sqrt(1 - y * y);
      const th = golden * i;
      const x = Math.cos(th) * r;
      const z = Math.sin(th) * r;
      const lat = Math.asin(y) * 180 / Math.PI;
      const lng = Math.atan2(z, x) * 180 / Math.PI;
      pts.push({ x, y, z, kind: isLand(lat, lng) ? "land" : "sea" });
    }

    let rot = 0;
    let last = performance.now();
    let raf = 0;
    let running = false;
    let onScreen = false;

    // Pre-allocated scratch buffers for the visible land dots (reused each frame
    // so we don't allocate / churn the GC on every render).
    const sxArr = new Float32Array(pts.length);
    const syArr = new Float32Array(pts.length);
    const dpArr = new Float32Array(pts.length);
    const buckets = [
      { max: 0.4, r: 0.9, color: "rgba(220,230,245,0.30)" },
      { max: 0.7, r: 1.4, color: "rgba(220,230,245,0.60)" },
      { max: 1.1, r: 1.9, color: "rgba(225,235,250,0.92)" },
    ];

    function render() {
      ctx.clearRect(0, 0, W, H);

      // Outer atmosphere glow
      const glow = ctx.createRadialGradient(CX, CY, R * 0.85, CX, CY, R * 1.15);
      glow.addColorStop(0, "rgba(120,200,255,0.0)");
      glow.addColorStop(0.55, "rgba(120,200,255,0.10)");
      glow.addColorStop(1, "rgba(120,200,255,0)");
      ctx.fillStyle = glow;
      ctx.beginPath(); ctx.arc(CX, CY, R * 1.15, 0, Math.PI * 2); ctx.fill();

      // Rim
      ctx.strokeStyle = "rgba(220,235,255,0.35)";
      ctx.lineWidth = 1.2;
      ctx.beginPath(); ctx.arc(CX, CY, R, 0, Math.PI * 2); ctx.stroke();

      // Dark sphere base
      const base = ctx.createRadialGradient(CX - R * 0.35, CY - R * 0.4, R * 0.1, CX, CY, R * 1.05);
      base.addColorStop(0, "#0b1426");
      base.addColorStop(0.6, "#050810");
      base.addColorStop(1, "#02030a");
      ctx.fillStyle = base;
      ctx.beginPath(); ctx.arc(CX, CY, R * 0.995, 0, Math.PI * 2); ctx.fill();

      // Rotate + project the visible land points once into the scratch buffers.
      const cosR = Math.cos(rot), sinR = Math.sin(rot);
      let n = 0;
      for (let i = 0; i < pts.length; i++) {
        const p = pts[i];
        if (p.kind !== "land") continue;
        const zr = p.x * sinR + p.z * cosR;
        if (zr < 0.02) continue; // back hemisphere
        const xr = p.x * cosR - p.z * sinR;
        sxArr[n] = CX + xr * R;
        syArr[n] = CY - p.y * R;
        dpArr[n] = zr;
        n++;
      }

      // Draw the dots in 3 depth buckets — one fill() per bucket instead of one
      // per dot. Turns thousands of draw calls into three.
      for (let b = 0; b < buckets.length; b++) {
        const lo = b === 0 ? 0 : buckets[b - 1].max;
        const bk = buckets[b];
        ctx.fillStyle = bk.color;
        ctx.beginPath();
        for (let i = 0; i < n; i++) {
          const d = dpArr[i];
          if (d < lo || d >= bk.max) continue;
          const sx = sxArr[i], sy = syArr[i];
          ctx.moveTo(sx + bk.r, sy);
          ctx.arc(sx, sy, bk.r, 0, Math.PI * 2);
        }
        ctx.fill();
      }

      // Subtle terminator shading
      const term = ctx.createLinearGradient(CX - R, CY, CX + R, CY);
      term.addColorStop(0, "rgba(0,0,0,0.55)");
      term.addColorStop(0.45, "rgba(0,0,0,0.0)");
      term.addColorStop(1, "rgba(0,0,0,0.0)");
      ctx.save();
      ctx.beginPath(); ctx.arc(CX, CY, R, 0, Math.PI * 2); ctx.clip();
      ctx.fillStyle = term; ctx.fillRect(CX - R, CY - R, R * 2, R * 2);
      ctx.restore();
    }

    // Cap rendering to ~30fps (a slow globe doesn't need 60) while keeping the
    // rotation speed wall-clock accurate regardless of frame timing.
    const FRAME_MS = 1000 / 30;
    let acc = 0;
    function loop(now) {
      if (!running) return;
      let dt = (now - last) / 1000; last = now;
      if (dt > 0.1) dt = 0.1;   // clamp after a pause so it doesn't jump
      rot += dt * 0.21;         // slow, elegant spin (~30s per revolution)
      acc += dt * 1000;
      raf = requestAnimationFrame(loop);
      if (acc >= FRAME_MS) { acc = 0; render(); }
    }

    // Only animate while the globe is actually on screen and the tab is visible.
    // This keeps it off the CPU when scrolled away or in Professional mode.
    function start() {
      if (running) return;
      running = true;
      last = performance.now();
      acc = FRAME_MS; // render on the first tick
      raf = requestAnimationFrame(loop);
    }
    function stop() {
      running = false;
      cancelAnimationFrame(raf);
    }
    function sync() {
      if (onScreen && !document.hidden) start();
      else stop();
    }

    const io = new IntersectionObserver((entries) => {
      onScreen = entries[0].isIntersecting;
      sync();
    }, { threshold: 0.01 });
    io.observe(cvs);
    document.addEventListener("visibilitychange", sync);

    // Always paint one static frame so a paused / reduced-motion globe looks right.
    render();

    return () => {
      stop();
      io.disconnect();
      document.removeEventListener("visibilitychange", sync);
    };
  }, []);

  return (
    <div className={"globe-wrap " + className}>
      <canvas ref={ref} width={size} height={size} />
    </div>
  );
}
